GraduationProject/Areas/Company/Controllers/MainController.cs
using Domain.Entities;
using Domain.Interfaces;
using GraduationProject.Areas.Company.ViewModels;
using GraduationProject.Areas.University.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace GraduationProject.Areas.Company.Controllers
{
    [Area("company")]
    [Authorize(Roles = "company")]
    public class MainController : Controller
    {
        private IUnitOfWork unitOfWork;
        private UserManager<Account> userManager;
        public MainController(IUnitOfWork _unitOfWork, UserManager<Account> _userManager)
        {
            unitOfWork = _unitOfWork;
            userManager = _userManager;
        }
        public IActionResult Default()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                ViewData["Posts"] = unitOfWork.Training.CountByCo((int)HttpContext.Session.GetInt32("CompanyId"));
                ViewData["Applications"] = unitOfWork.Application.CountByCo((int)HttpContext.Session.GetInt32("CompanyId"));
                ViewData["Trainees"] = unitOfWork.Student.TraineeCountByCo((int)HttpContext.Session.GetInt32("CompanyId"));
                var co = unitOfWork.Company.GetById((int)HttpContext.Session.GetInt32("CompanyId"));
                ViewData["CompanyName"] = co.CompanyName;
                IEnumerable<Application> model = unitOfWork.Application.GetApplicationsByCompanyId(co.CompanyId);
                return View(model);
            }
        }
        public IActionResult Messages()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                return View();
            }
        }
        [HttpGet]
        public IActionResult Profile()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                var co = unitOfWork.Company.GetById((int)HttpContext.Session.GetInt32("CompanyId"));
                CompanyProfileEditViewModel model = new CompanyProfileEditViewModel
                {
                    CompanyInfo = co.CompanyInfo,
                    CompanyName = co.CompanyName,
                    CompanyEmail = co.CompanyEmail,
                    Image = co.Image,
                    CompanyLocation = co.CompanyLocation
                };
                return View(model);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Profile(CompanyProfileEditViewModel model, IFormFile image, [FromServices] IWebHostEnvironment env)
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var co = unitOfWork.Company.GetById((int)HttpContext.Session.GetInt32("CompanyId"));
                    co.CompanyName = model.CompanyName;
                    co.CompanyEmail = model.CompanyEmail;
                    co.CompanyInfo = model.CompanyInfo;
                    if (image != null && image.Length > 0)
                    {
                      Account acc =  await userManager.GetUserAsync(User);
                        var imagePath = Path.Combine(env.WebRootPath, "uploads", image.FileName);
                        using (var stream = new FileStream(imagePath, FileMode.Create))
                        {
                            await image.CopyToAsync(stream);
                        }
                        co.Image = "/uploads/" + image.FileName;
                        model.Image = co.Image;
                        acc.AccountImage = co.Image;
                        await userManager.UpdateAsync(acc);
                    }
                    unitOfWork.Company.Update(co);
                    unitOfWork.Complete();
                }
                return View(model);
            }
        }
        [HttpGet]
        public IActionResult ChangePassword()
        {
			if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
			{
				TempData["SessionTimeOut"] = "Your Session has ended";
				return RedirectToAction("Logout", "Account", new { area = "" });
			}
            else
            {
                return View();
            }
		}
        [HttpPost]
		public async Task<IActionResult> ChangePassword(ViewModels.ChangePassViewModel model)
		{
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
			{
				if (ModelState.IsValid)
				{
					Account acc = await userManager.GetUserAsync(User);
					var result = await userManager.ChangePasswordAsync(acc, model.Current, model.New);
					if (result.Succeeded)
					{
						TempData["Changed"] = "Password Changed Successfully";
						return RedirectToAction("Default");
					}
					ViewBag.err = "Something went wrong, Please try again!";
					return View(model);
				}
				return View(model);
			}
		}
		public IActionResult About()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                return View();
            }
        }
    }
}

GraduationProject/Areas/Company/Controllers/TrainingController.cs
using DataAccess.EFCore.UnitOfWorks;
using Domain.Entities;
using Domain.Interfaces;
using GraduationProject.Areas.Company.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;

namespace GraduationProject.Areas.Company.Controllers
{
    [Area("company")]
    [Authorize(Roles = "company")]
    public class TrainingController : Controller
    {
        private IUnitOfWork unitOfWork;
        public TrainingController(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }
        public IActionResult Posts()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                List<Training> model = unitOfWork.Training.GetAllByCo((int)HttpContext.Session.GetInt32("CompanyId"));
                return View(model);
            }
        }
        [HttpGet]
        public IActionResult AddPost()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                ViewBag.Categories = new SelectList(unitOfWork.Category.GetAll(), "CategoryId", "CategoryName");
                return View();
            }
        }
        [HttpPost]
        public IActionResult AddPost(AddPostViewModel model)
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                if (ModelState.IsValid)
                {
                    Training training = new Training
                    {
                        CategoryId = model.CategoryId,
                        StartDate = model.StartDate,
                        EndDate = model.EndDate,
                        TrainingTitle = model.TrainingTitle,
                        TrainingDetails = model.TrainingDetails,
                        TrainingLocation = model.TrainingLocation,
                        CompanyId = (int)HttpContext.Session.GetInt32("CompanyId"),
                        isAvailable = true
                    };
                    unitOfWork.Training.Add(training);
                    unitOfWork.Complete();
                    return RedirectToAction("Posts");
                }
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult EditPost(int PostId)
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                ViewBag.Categories = new SelectList(unitOfWork.Category.GetAll(), "CategoryId", "CategoryName");
                Training model = unitOfWork.Training.GetById(PostId);
                if ((int)HttpContext.Session.GetInt32("CompanyId") != model.CompanyId)
                {
                    return NotFound();
                }
                return View(model);
            }
        }
        [HttpPost]
        public IActionResult EditPost(Training model)
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                if (ModelState.IsValid)
                {
                    model.CompanyId = (int)HttpContext.Session.GetInt32("CompanyId");
                    model.isAvailable = true;
                    unitOfWork.Training.Update(model);
                    unitOfWork.Complete();
                    return RedirectToAction("Posts");
                }
                return View(model);
            }
        }
        public IActionResult HidePost(int PostId)
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                Training model = unitOfWork.Training.GetById(PostId);
                if ((int)HttpContext.Session.GetInt32("CompanyId") != model.CompanyId)
                {
                    return NotFound();
                }
                model.isAvailable = false;
                unitOfWork.Training.Update(model);
                unitOfWork.Complete();
                return RedirectToAction("Posts");
            }
        }
        public IActionResult ShowPost(int PostId)
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                Training model = unitOfWork.Training.GetById(PostId);
                if ((int)HttpContext.Session.GetInt32("CompanyId") != model.CompanyId)
                {
                    return NotFound();
                }
                model.isAvailable = true;
                unitOfWork.Training.Update(model);
                unitOfWork.Complete();
                return RedirectToAction("Posts");
            }
        }
    }
}

GraduationProject/Areas/Company/Views/Shared/_Layout.cshtml
@inject SignInManager<Account> signInManager
@inject UserManager<Account> userManager
@{
    var user = await userManager.GetUserAsync(User);
}
<!DOCTYPE html>
<html lang="en" class="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Intern.JO - @ViewData["Title"]</title>

    <link rel="stylesheet" href="~/Dashboard/css/main.css?v=1628755089081">
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.9.95/css/materialdesignicons.min.css">
    <link rel="apple-touch-icon" sizes="180x180" href="~/Dashboard/nivapple-touch-icon.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon.ico" />
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon.ico" />
    <link rel="mask-icon" href="~/Dashboard/safari-pinned-tab.svg" color="#00b4b6" />
    <link rel="stylesheet" href="~/css/Animate/animate.min.css" />
    <meta name="description" content="Admin One - free Tailwind dashboard">

    <meta property="og:url" content="https://justboil.github.io/admin-one-tailwind/">
    <meta property="og:site_name" content="JustBoil.me">
    <meta property="og:title" content="Admin One HTML">
    <meta property="og:description" content="Admin One - free Tailwind dashboard">
    <meta property="og:image" content="https://justboil.me/images/one-tailwind/repository-preview-hi-res.png">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1920">
    <meta property="og:image:height" content="960">

    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:title" content="Admin One HTML">
    <meta property="twitter:description" content="Admin One - free Tailwind dashboard">
    <meta property="twitter:image:src" content="https://justboil.me/images/one-tailwind/repository-preview-hi-res.png">
    <meta property="twitter:image:width" content="1920">
    <meta property="twitter:image:height" content="960">

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-130795909-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());
        gtag('config', 'UA-130795909-1');
    </script>

</head>
<body>
    <div id="app">

        <nav id="navbar-main" class="navbar is-fixed-top">
            <div class="navbar-brand">
                <a class="navbar-item mobile-aside-button">
                    <span class="icon"><i class="mdi mdi-forwardburger mdi-24px"></i></span>
                </a>
                <div class="navbar-item">
                    <div class="control"><input placeholder="Search..." class="input"></div>
                </div>
            </div>
            <div class="navbar-brand is-right">
                <a class="navbar-item --jb-navbar-menu-toggle" data-target="navbar-menu">
                    <span class="icon"><i class="mdi mdi-dots-vertical mdi-24px"></i></span>
                </a>
            </div>
            <div class="navbar-menu" id="navbar-menu">
                <div class="navbar-end">
                    <div class="navbar-item dropdown has-divider has-user-avatar">
                        <a class="navbar-link">
                            <div class="user-avatar">
                                <img src="@Url.Content(user.AccountImage)" alt="@user.FullName - avatar" class="rounded-full">
                            </div>
                            <div class="is-user-name"><span>@user.FullName</span></div>
                            <span class="icon"><i class="mdi mdi-chevron-down"></i></span>
                        </a>
                        <div class="navbar-dropdown">
                            <a class="navbar-item" asp-action="ChangePassword" asp-controller="Main">
                                <span class="icon"><i class="mdi mdi-settings"></i></span>
                                <span>Change Password</span>
                            </a>
                            <hr class="navbar-divider">
                            <a asp-action="Logout" asp-controller="Account" asp-area="" class="navbar-item">
                                <span class="icon"><i class="mdi mdi-logout"></i></span>
                                <span>Log Out</span>
                            </a>
                        </div>
                    </div>
                    <a asp-action="About" asp-controller="Main" class="navbar-item has-divider desktop-icon-only">
                        <span class="icon"><i class="mdi mdi-help-circle-outline"></i></span>
                        <span>About</span>
                    </a>
                    <a title="Log out" asp-action="Logout" asp-controller="Account" asp-area="" class="navbar-item desktop-icon-only">
                        <span class="icon"><i class="mdi mdi-logout"></i></span>
                        <span>Log out</span>
                    </a>
                </div>
            </div>
        </nav>

        <aside class="aside is-placed-left is-expanded">
            <div class="aside-tools">
                <div>
                    Intern.JO <b class="font-black">Company</b>
                </div>
            </div>
            <div class="menu is-menu-main">
                <p class="menu-label">General</p>
                <ul class="menu-list">
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Default"?"active":"")">
                        <a asp-action="Default" asp-controller="Main">
                            <span class="icon"><i class="mdi mdi-home-variant"></i></span>
                            <span class="menu-item-label">Home</span>
                        </a>
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Messages"?"active":"")">
                        <a asp-action="Messages" asp-controller="Main">
                            <span class="icon"><i class="mdi mdi-message"></i></span>
                            <span class="menu-item-label">Messages</span>
                        </a>
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Profile"?"active":"")">
                        <a asp-action="Profile" asp-controller="Main">
                            <span class="icon"><i class="mdi mdi-account-circle"></i></span>
                            <span class="menu-item-label">Profile</span>
                        </a>
                    </li>
                </ul>
                <p class="menu-label">Training Management</p>
                @{
                    string s = ViewContext.RouteData.Values["Action"].ToString();
                }
                <ul class="menu-list">
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Posts"?"active":"")">
                        <a asp-action="Posts" asp-controller="Training">
                            <span class="icon"><i class="mdi mdi-post"></i></span>
                            <span class="menu-item-label">Posts</span>
                        </a>
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Applications"?"active":"")">
                        <a asp-action="Applications" asp-controller="Applications">
                            <span class="icon"><i class="mdi mdi-account-box-multiple"></i></span>
                            <span class="menu-item-label">Applications</span>
                        </a>
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Trainees"?"active":"")">
                        <a asp-action="Trainees" asp-controller="Applications">
                            <span class="icon"><i class="mdi mdi-school"></i></span>
                            <span class="menu-item-label">Trainees</span>
                        </a>
                    </li>
                </ul>
                
                <p class="menu-label">About</p>
                <ul class="menu-list">
                    <li class= "@(ViewContext.RouteData.Values["Action"].ToString() == "About" ? "active" : "")">
                        <a asp-action="About" asp-controller="Main" class="has-icon">
                            <span class="icon"><i class="mdi mdi-help-circle"></i></span>
                            <span class="menu-item-label">About</span>
                        </a>
                    </li>
                </ul>
            </div>
        </aside>

        <section class="is-title-bar">
            <div class="flex flex-col md:flex-row items-center justify-between space-y-6 md:space-y-0">
                <ul>
                    <li>@user.FullName</li>
                    <li>Dashboard</li>
                </ul>
            </div>
        </section>

        @*<section class="is-hero-bar">
        <div class="flex flex-col md:flex-row items-center justify-between space-y-6 md:space-y-0">
        <h1 class="title">
        Dashboard
        </h1>
        <button class="button light">Button</button>
        </div>
        </section>*@

        <section class="section main-section animate__backInUp">
            @RenderBody()
        </section>

        <footer class="footer">
            <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0">
                <div class="flex items-center justify-start space-x-3">
                    <div>
                        © 2023, Intern.JO |
                    </div>

                    <div>
                        <p><a href="#" target="_blank">Development Maestros</a></p>
                    </div>
                </div>
            </div>
        </footer>

        @*<div id="sample-modal" class="modal">
            <div class="modal-background --jb-modal-close"></div>
            <div class="modal-card">
                <header class="modal-card-head">
                    <p class="modal-card-title">Sample modal</p>
                </header>
                <section class="modal-card-body">
                    <p>Lorem ipsum dolor sit amet <b>adipiscing elit</b></p>
                    <p>This is sample modal</p>
                </section>
                <footer class="modal-card-foot">
                    <button class="button --jb-modal-close">Cancel</button>
                    <button class="button red --jb-modal-close">Confirm</button>
                </footer>
            </div>
        </div>

        <div id="sample-modal-2" class="modal">
            <div class="modal-background --jb-modal-close"></div>
            <div class="modal-card">
                <header class="modal-card-head">
                    <p class="modal-card-title">Sample modal</p>
                </header>
                <section class="modal-card-body">
                    <p>Lorem ipsum dolor sit amet <b>adipiscing elit</b></p>
                    <p>This is sample modal</p>
                </section>
                <footer class="modal-card-foot">
                    <button class="button --jb-modal-close">Cancel</button>
                    <button class="button blue --jb-modal-close">Confirm</button>
                </footer>
            </div>
        </div>*@

    </div>

    <script type="text/javascript" src="~/Dashboard/js/main.min.js?v=1628755089081"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/popper.min.js"></script>

    <script>
        !function (f, b, e, v, n, t, s) {
            if (f.fbq) return; n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n; n.push = n; n.loaded = !0; n.version = '2.0';
            n.queue = []; t = b.createElement(e); t.async = !0;
            t.src = v; s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '658339141622648');
        fbq('track', 'PageView');
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>