GraduationProject/Areas/Company/Controllers/MainController.cs
using Domain.Entities;
using Domain.Interfaces;
using GraduationProject.Areas.Company.ViewModels;
using GraduationProject.Areas.University.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace GraduationProject.Areas.Company.Controllers
{
    [Area("company")]
    [Authorize(Roles = "company")]
    public class MainController : Controller
    {
        private IUnitOfWork unitOfWork;
        private UserManager<Account> userManager;
        public MainController(IUnitOfWork _unitOfWork, UserManager<Account> _userManager)
        {
            unitOfWork = _unitOfWork;
            userManager = _userManager;
        }
        public IActionResult Default()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                ViewData["Posts"] = unitOfWork.Training.CountByCo((int)HttpContext.Session.GetInt32("CompanyId"));
                ViewData["Applications"] = unitOfWork.Application.CountByCo((int)HttpContext.Session.GetInt32("CompanyId"));
                ViewData["Trainees"] = unitOfWork.Student.TraineeCountByCo((int)HttpContext.Session.GetInt32("CompanyId"));
                var co = unitOfWork.Company.GetById((int)HttpContext.Session.GetInt32("CompanyId"));
                ViewData["CompanyName"] = co.CompanyName;
                IEnumerable<Application> model = unitOfWork.Application.GetApplicationsByCompanyId(co.CompanyId);
                return View(model);
            }
        }
        public IActionResult Messages()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                return View();
            }
        }
        [HttpGet]
        public IActionResult Profile()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                var co = unitOfWork.Company.GetById((int)HttpContext.Session.GetInt32("CompanyId"));
                CompanyProfileEditViewModel model = new CompanyProfileEditViewModel
                {
                    CompanyInfo = co.CompanyInfo,
                    CompanyName = co.CompanyName,
                    CompanyEmail = co.CompanyEmail,
                    Image = co.Image,
                    CompanyLocation = co.CompanyLocation
                };
                return View(model);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Profile(CompanyProfileEditViewModel model, IFormFile image, [FromServices] IWebHostEnvironment env)
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var co = unitOfWork.Company.GetById((int)HttpContext.Session.GetInt32("CompanyId"));
                    co.CompanyName = model.CompanyName;
                    co.CompanyEmail = model.CompanyEmail;
                    co.CompanyInfo = model.CompanyInfo;
                    if (image != null && image.Length > 0)
                    {
                      Account acc =  await userManager.GetUserAsync(User);
                        var imagePath = Path.Combine(env.WebRootPath, "uploads", image.FileName);
                        using (var stream = new FileStream(imagePath, FileMode.Create))
                        {
                            await image.CopyToAsync(stream);
                        }
                        co.Image = "/uploads/" + image.FileName;
                        model.Image = co.Image;
                        acc.AccountImage = co.Image;
                        await userManager.UpdateAsync(acc);
                    }
                    unitOfWork.Company.Update(co);
                    unitOfWork.Complete();
                }
                return View(model);
            }
        }
        [HttpGet]
        public IActionResult ChangePassword()
        {
			if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
			{
				TempData["SessionTimeOut"] = "Your Session has ended";
				return RedirectToAction("Logout", "Account", new { area = "" });
			}
            else
            {
                return View();
            }
		}
        [HttpPost]
		public async Task<IActionResult> ChangePassword(ViewModels.ChangePassViewModel model)
		{
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
			{
				if (ModelState.IsValid)
				{
					Account acc = await userManager.GetUserAsync(User);
					var result = await userManager.ChangePasswordAsync(acc, model.Current, model.New);
					if (result.Succeeded)
					{
						TempData["Changed"] = "Password Changed Successfully";
						return RedirectToAction("Default");
					}
					ViewBag.err = "Something went wrong, Please try again!";
					return View(model);
				}
				return View(model);
			}
		}
		public IActionResult About()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("CompanyId") || HttpContext.Session.GetInt32("CompanyId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                return View();
            }
        }
    }
}

GraduationProject/Areas/University/Controllers/StudentsController.cs
using Domain.Entities;
using Domain.Interfaces;
using GraduationProject.Areas.University.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace GraduationProject.Areas.University.Controllers
{
    [Area("university")]
    [Authorize(Roles = "uniSupervisor")]
    public class StudentsController : Controller
    {
        private IUnitOfWork unitOfWork;
        private UserManager<Account> userManager;
        public StudentsController(IUnitOfWork _unitOfWork, UserManager<Account> _userManager)
        {
            unitOfWork = _unitOfWork;
            userManager = _userManager;
        }
        public IActionResult AllStudents()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("SupervisorId") || HttpContext.Session.GetInt32("SupervisorId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                AllStudentsViewModel model = new AllStudentsViewModel
                {
                    Active = unitOfWork.Student.GetStudentsByUni((int)HttpContext.Session.GetInt32("UniversityId")),
                    NonActive = unitOfWork.Student.GetNotActiveStudents((int)HttpContext.Session.GetInt32("UniversityId"))
                };
                return View(model);
            }
        }
        public IActionResult TraineeStudents()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("SupervisorId") || HttpContext.Session.GetInt32("SupervisorId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                IEnumerable<Student> model = unitOfWork.Student.GetTraineeStudents((int)HttpContext.Session.GetInt32("UniversityId"));
                return View(model);
            }
        }
        public IActionResult NotTraineeStudents()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("SupervisorId") || HttpContext.Session.GetInt32("SupervisorId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                IEnumerable<Student> model = unitOfWork.Student.GetNotTrainee((int)HttpContext.Session.GetInt32("UniversityId"));
                return View(model);
            }
        }
        public IActionResult StudentEmails()
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("SupervisorId") || HttpContext.Session.GetInt32("SupervisorId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                ViewBag.err = TempData["Error"] as string;
                ViewBag.oneErr = TempData["OneError"] as string;
                IEnumerable<StudentEmail> model = unitOfWork.StudentEmails.GetStudentEmails((int)HttpContext.Session.GetInt32("UniversityId"));
                return View(model);
            }
        }

        [HttpPost]
        public IActionResult AddEmails(IFormFile file)
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("SupervisorId") || HttpContext.Session.GetInt32("SupervisorId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                var data = new List<string>();
                try
                {
                    using (var package = new ExcelPackage(file.OpenReadStream()))
                    {
                        var worksheet = package.Workbook.Worksheets[0];
                        var rowCount = worksheet.Dimension.Rows;

                        // Loop through each row and get the value of the first column
                        for (int row = 1; row <= rowCount; row++)
                        {
                            var cellValue = worksheet.Cells[row, 1].Value?.ToString();
                            if (!string.IsNullOrEmpty(cellValue))
                            {
                                if (unitOfWork.StudentEmails.isExists(cellValue))
                                {
                                    TempData["OneError"] = "Some data already exists";
                                    continue;
                                }
                                data.Add(cellValue);
                            }
                        }
                    }
                    unitOfWork.StudentEmails.AddStudentEmails(data, (int)HttpContext.Session.GetInt32("UniversityId"));
                    unitOfWork.Complete();
                }
                catch
                {
                    TempData["Error"] = "Something went wrong please check you excel sheet and try again!";
                }
                return RedirectToAction("StudentEmails");
            }
        }

        [HttpPost]
        public IActionResult AddEmail(string email)
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("SupervisorId") || HttpContext.Session.GetInt32("SupervisorId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                if (email == null)
                {
                    TempData["Error"] = "You didnt insert an email!";
                    return RedirectToAction("StudentEmails");
                }
                else
                {
                    if (unitOfWork.StudentEmails.isExists(email))
                    {
                        TempData["OneError"] = "Email Already exists";
                        return RedirectToAction("StudentEmails");
                    }
                    StudentEmail se = new StudentEmail
                    {
                        Email = email,
                        isCreated = false,
                        UniversityId = (int)HttpContext.Session.GetInt32("UniversityId")
                    };

                    unitOfWork.StudentEmails.Add(se);
                    unitOfWork.Complete();
                    return RedirectToAction("StudentEmails");
                }
            }
        }

        public IActionResult DeleteEmail(int id)
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("SupervisorId") || HttpContext.Session.GetInt32("SupervisorId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                StudentEmail email = unitOfWork.StudentEmails.GetById(id);
                unitOfWork.StudentEmails.RemoveStudentEmail(email);
                int result = unitOfWork.Complete();
                if (result == 0)
                {
                    TempData["Error"] = "Something went wrong please try again!";
                }
                return RedirectToAction("StudentEmails");
            }
        }

        public IActionResult StudentProfile(int id, bool isTrainee)
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("SupervisorId") || HttpContext.Session.GetInt32("SupervisorId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                Student student;
                if (isTrainee)
                {
                    student = unitOfWork.Student.getStudentWithTraining(id);
                    ViewBag.ReportExists = unitOfWork.Report.isExists(student.StudentId);
                }
                else
                {
                    student = unitOfWork.Student.GetById(id);
                }
                return View(student);
            }
        }
        public IActionResult Report(int id)
        {
            if (HttpContext.Session == null || !HttpContext.Session.Keys.Contains("SupervisorId") || HttpContext.Session.GetInt32("SupervisorId") == null)
            {
                TempData["SessionTimeOut"] = "Your Session has ended";
                return RedirectToAction("Logout", "Account", new { area = "" });
            }
            else
            {
                return View(unitOfWork.Report.getByStudentId(id));
            }
        }
    }
}

GraduationProject/Areas/University/Views/Main/About.cshtml
@{
    ViewData["Title"] = "About";
}

<h1 class="About">Development Maestros</h1>
<div class="team-details">
	<div class="detail">
		<h2>About Us</h2>
		<p>We are a team of undergraduate students who are passionate about web development. Our focus is on using the latest technologies to build high-quality web applications that solve real-world problems.</p>
	</div>
	<div class="detail">
		<h2>Expertise</h2>
		<p>Our team has expertise in ASP.NET Core, HTML, CSS, JavaScript, and SQL Server. We are always eager to learn new technologies and stay up-to-date with the latest industry trends.</p>
	</div>
	<div class="detail">
		<h2>Projects</h2>
		<p>We have worked on a variety of projects, including e-commerce websites, social networking platforms, and business management systems. We are always looking for new challenges and opportunities to use our SoftSkills.</p>
	</div>
</div>
<div class="contact-details">
	<h2>Contact Us</h2>
	<p>If you have any questions or would like to discuss a potential project, please feel free to contact us:</p>
	<p>Email: <a href="mailto:devmaestros@example.com">dev@maestros.com</a></p>
	<p>Phone: <a href="tel:555-555-5555">555-555-5555</a></p>
</div>

GraduationProject/Areas/University/Views/Main/ChangePassword.cshtml
@model ChangePassViewModel
@{
    ViewData["Title"] = "ChangePassword";
}


<div class="card">
    <header class="card-header">
        <p class="card-header-title">
            <span class="icon"><i class="mdi mdi-lock"></i></span>
            Change Password  <div asp-validation-summary="All" style="color:red;"></div>
            <span style="color:red;">@ViewBag.err</span>
        </p>
    </header>
    <div class="card-content">
        <form asp-action="ChangePassword" asp-controller="Main">
            <div class="field">
                <label class="label">Current password</label>
                <div class="control">
                    <input asp-for="Current" class="input">
                </div>
                <p class="help"><span asp-validation-for="Current" style="color:red;"></span></p>
                <p class="help">Required. Your current password</p>
            </div>
            <hr>
            <div class="field">
                <label class="label">New password</label>
                <div class="control">
                    <input asp-for="New" class="input">
                </div>
                <p class="help"> <span asp-validation-for="New" style="color:red;"></span></p>
                <p class="help">Required. New password</p>
            </div>
            <div class="field">
                <label class="label">Confirm password</label>
                <div class="control">
                    <input asp-for="ConfirmNew" class="input">
                </div>
                <p class="help"><span asp-validation-for="ConfirmNew" style="color:red;"></span></p>
                <p class="help">Required. New password one more time</p>
            </div>
            <hr>
            <div class="field">
                <div class="control">
                    <button type="submit" class="button green">
                        Submit
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

GraduationProject/Areas/University/Views/Main/Companies.cshtml
@model IEnumerable<Company>
@{
    ViewData["Title"] = "Companies";
}

<section class="is-hero-bar">
    <div class="flex flex-col md:flex-row items-center justify-between space-y-6 md:space-y-0">
        <h1 class="title">
            All companies
        </h1>
    </div>
</section>
@if (Model.Any())
{
    <div class="card has-table" style="margin-top:20px">
        <header class="card-header">
            <p class="card-header-title">
                <span class="icon"><i class="mdi mdi-account-multiple"></i></span>
                Companies
            </p>
            <a asp-action="Companies" class="card-header-icon">
                <span class="icon"><i class="mdi mdi-reload"></i></span>
            </a>
        </header>
        <div class="card-content">
            <table>
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Info</th>
                        <th>Location</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="image-cell">
                                <div class="image">
                                    <img src="@Url.Content(item.Image)" class="rounded-full">
                                </div>
                            </td>
                            <td data-label="Name">@item.CompanyName</td>
                            <td data-label="Company">@item.Account.Email</td>
                            <td data-label="City">@item.CompanyInfo</td>
                            <td data-label="City">@item.CompanyLocation</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}
else
{
    <div class="card empty">
        <div class="card-content">
            <div>
                <span class="icon large"><i class="mdi mdi-emoticon-sad mdi-48px"></i></span>
            </div>
            <p>Nothing here</p>
        </div>
    </div>
}

GraduationProject/Areas/University/Views/Main/Default.cshtml
@model IEnumerable<Student>
@{
    ViewData["Title"] = "Default";
}
<section class="is-hero-bar">
    <div class="flex flex-col md:flex-row items-center justify-between space-y-6 md:space-y-0">
        <h1 class="title">
            Field Training Dashboard | @ViewData["UniversityName"] <span style="color:green">@ViewBag.changed</span>
        </h1>
    </div>
</section>
<div class="grid gap-6 grid-cols-1 md:grid-cols-3 mb-6">
    <div class="card">
        <div class="card-content">
            <div class="flex items-center justify-between">
                <div class="widget-label">
                    <h3>
                        Trainees
                    </h3>
                    <h1>
                        @ViewData["Trainee"]
                    </h1>
                </div>
                <span class="icon widget-icon text-green-500"><i class="mdi mdi-school mdi-48px"></i></span>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-content">
            <div class="flex items-center justify-between">
                <div class="widget-label">
                    <h3>
                        Not Trainee
                    </h3>
                    <h1>
                        @ViewData["NotTrainee"]
                    </h1>
                </div>
                <span class="icon widget-icon text-blue-500"><i class="mdi mdi-account-multiple mdi-48px"></i></span>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-content">
            <div class="flex items-center justify-between">
                <div class="widget-label">
                    <h3>
                        Companies
                    </h3>
                    <h1>
                        @ViewData["Companies"]
                    </h1>
                </div>
                <span class="icon widget-icon text-red-500"><i class="mdi mdi-domain mdi-48px"></i></span>
            </div>
        </div>
    </div>
</div>
@if (Model.Any())
{
    <div class="card has-table">
        <header class="card-header">
            <p class="card-header-title">
                <span class="icon"><i class="mdi mdi-account-multiple"></i></span>
                Trainees
            </p>
            <a asp-action="Default" class="card-header-icon">
                <span style="font-size: 20px;" class="icon"><i class="mdi mdi-reload"></i></span>
            </a>
        </header>
        <div class="card-content">
            <table>
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Training Company</th>
                        <th>Training Location</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="image-cell">
                                <div class="image">
                                    <img src="@Url.Content(item.Image)" class="rounded-full">
                                </div>
                            </td>
                            <td data-label="Name">@item.StudentName</td>
                            <td data-label="Name">@item.StudentEmail</td>
                            <td data-label="Company">@item.Training.Company.CompanyName</td>
                            <td data-label="City">@item.Training.TrainingLocation</td>
                            <td class="actions-cell">
                                <div class="buttons right nowrap">
                                    <a asp-action="StudentProfile" asp-controller="Students" asp-route-id="@item.StudentId" asp-route-isTrainee="@item.isTrainee" class="button small green --jb-modal" data-target="sample-modal-2" type="button">
                                        <span style="font-size: 25px;" class="icon"><i class="mdi mdi-account-circle"></i></span>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}
else
{
    <div class="card empty" style="margin-top:20px">
        <div class="card-content">
            <div>
                <span class="icon large">
                    <i class="mdi mdi-emoticon-sad mdi-48px"></i>
                    </span>
            </div>
            <p>No Trainee Students Found</p>
        </div>
    </div>
}

GraduationProject/Areas/University/Views/Main/Messages.cshtml
@{
    ViewData["Title"] = "Messages";
}

<div class="head-section">
    <div class="headLeft-section">
        <div class="headLeft-sub">
            <input type="text" name="search" placeholder="Search...">
            <button> <i class="mdi mdi-magnify"></i> </button>
        </div>
    </div>
    <div class="headRight-section">
        <div class="headRight-sub">
            <h3>Orange</h3>
            <small>Orange Coding School</small>
        </div>
    </div>
</div>
<div class="body-section">
    <div class="left-section mCustomScrollbar" data-mcs-theme="minimal-dark">
        <ul>
            <li class="active">
                <div class="chatList">
                    <div class="img">
                        <img src="~/Images/Orange.png">
                    </div>
                    <div class="desc">
                        <small class="time">05:30 am</small>
                        <h5>Orange</h5>
                        <small>Orange Coding School</small>
                    </div>
                </div>
            </li>
            <li>
                <div class="chatList">
                    <div class="img">
                        <img src="~/Images/Maestors.png">
                    </div>
                    <div class="desc">
                        <small class="time">3 day</small>
                        <h5>Dev Maestros</h5>
                        <small>Development Team</small>
                    </div>
                </div>
            </li>
            <li>
                <div class="chatList">
                    <div class="img">
                        <img src="~/Images/Estarta.jpg">
                    </div>
                    <div class="desc">
                        <small class="time">3 day</small>
                        <h5>Estarta</h5>
                        <small>Great Development Company!</small>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="right-section">
        <div class="message mCustomScrollbar" data-mcs-theme="minimal-dark">
            <ul>
                <li class="msg-left">
                    <div class="msg-left-sub">
                        <img src="~/Images/Orange.png">
                        <div class="msg-desc">
                            Hi, can you provide information on your training programs for our company?
                        </div>
                        <small>05:25 am</small>
                    </div>
                </li>
                <li class="msg-right">
                    <div class="msg-left-sub">
                        <img src="~/Images/HuLogo.png">
                        <div class="msg-desc">
                            Yes, we can customize programs to your needs. Want a brochure?
                        </div>
                        <small>05:25 am</small>
                    </div>
                </li>
                <li class="msg-day"><small>Wednesday</small></li>
                <li class="msg-left">
                    <div class="msg-left-sub">
                        <img src="~/Images/Orange.png">
                        <div class="msg-desc">
                            Yes, please. How long are the programs?
                        </div>
                        <small>05:25 am</small>
                    </div>
                </li>
                <li class="msg-right">
                    <div class="msg-left-sub">
                        <img src="~/Images/HuLogo.png">
                        <div class="msg-desc">
                            They can be a few days to several weeks. Let us know if you have questions. Thank you.
                        </div>
                        <small>05:25 am</small>
                    </div>
                </li>
            </ul>
        </div>
        <div class="right-section-bottom">
            <form>
                <div class="upload-btn">
                    <button class="btn"><i class="mdi mdi-image"></i></button>
                    <input type="file" name="myfile" />
                </div>
                <input type="text" name="" placeholder="type here...">
                <button class="btn-send"><i class="mdi mdi-send"></i></button>
            </form>
        </div>
    </div>
</div>